name = 'Base'
license = 'MIT'
licenselink = 'https://github.com/lubeso/hugo-theme-base/LICENSE'
description = 'Base'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/lubeso/hugo-theme-base'

# If the theme has a single author
[author]
  name = 'Luis Becerra Solis'
  homepage = 'www.lubeso.dev'
